wandb:
  project: rag_qa
scrape_wiki:
  scrape: all
  failed_parsing_list: not_parsed.txt
  pickled_dataset: dataset.pickle
make_embeddings:
  dataset_artifact: movies_dataset:latest
  pickled_dataset: dataset.pickle
  vector_store_filename: qdrant_vector_store.pickle
  pickled_chunks_filename: chunked_docs.pickle
upload_questions:
  qa_filenames:
    - movies_qa.yaml
    - more_movies_qa.yaml
ask_questions:
  vector_store_artifact: embeddings:latest
  vector_store_filename: qdrant_vector_store.pickle
  dataset_artifact: movies_dataset:latest
  qa_artifact: questions:latest
  qa_filenames:
    - movies_qa.yaml
